### ISSUE TITLE
Goal Detail screen

### ISSUE THREAD

**Issue by hurjun1995** [hurjun1995/yolo#15]
**Implement Goal Detail screen: used when user creates a goal.**

**Required fields:**
- Goal name
- starting day: default is "today"
- Time to log: user will get a notification to log the achievement on this goal at specified time.
    - ex. every 6PM
- Alarm(or notice) about the goal before logging time **(maximum 1 hour)**
- whether the goal is "intrinsic" vs "extrinsic"

**Nice to have:**
- goal category, if the goal is custom-made

**Comment by alice710** [comment]
Also, I'd like to add an alarm setting before logging (but no more than 1 hour notice).

**Comment by hurjun1995** [comment]
@alice710 Added in the main post!

**Comment by hurjun1995** [comment]
Need to add Alarm time to goal table: relative time to logging time, 0min< x < 60min

**Comment by hurjun1995** [comment]
whether the goal is "intrinsic" vs "extrinsic" will be asked in GoalSurvey screen.

Other fields are all implemented.
